//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEuler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problem
    {
        public int ProblemId { get; set; }
        public int Id { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string Answer { get; set; }
        public string Code { get; set; }
        public string Language { get; set; }
        public string FunctionName { get; set; }
    }
}
